[package]
name = "evapanel"
version = "0.1.1"
edition = "2021"
authors = ["Bohemia Automation", "Altertech"]
description = "EVA ICS HMI kiosk browser"
license = "propietary"

[dependencies]
wry = { version =  "0.17.0", features = ["devtools"] }
webkit2gtk = { version = "0.18", features = [ "v2_22" ] }
gio = "0.15"
clap = { version = "3.1.18", features = ["derive"] }
once_cell = "1.12.0"
bmart = "0.2.2"
env_logger = "0.9.0"
log = "0.4.17"
eva-common = { version = "0.1.139", features = ["payload", "elbus-rpc"] }
tokio = { version = "1.15.0", features = ["full"] }
elbus = { version = "0.2.0", features = ["broker", "rpc", "ipc"] }
async-trait = "0.1.53"
triggered = "0.1.2"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
shellexpand = "2.1.0"
hostname = "0.3.1"

[profile.release]
strip = true
lto = true
codegen-units = 1

