[target.x86_64-unknown-linux-gnu]
image.name = "evapanel-build-env-x86_64:latest"
image.toolchain = ["x86_64-unknown-linux-gnu"]

[target.aarch64-unknown-linux-gnu]
image.name = "evapanel-build-env-aarch64:latest"
image.toolchain = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
